export type VipPlan = {
  id: string;
  level: string; // e.g. "VIP 1", "VIP 2"...
  planName: string; // e.g. "Starter Plan"...
  minDeposit: number;
  dailyProfitPercent: number; // e.g. 10.00
  dailyProfitUsdtMin: number;
  durationDays: number;
  totalUsers: number;
  status: "Active" | "Inactive";
  referralBonus: {
    level1: number;
    level2: number;
    level3: number;
  };
};

export const initialVipPlans: VipPlan[] = [
  {
    id: "VP1",
    level: "VIP 1",
    planName: "Starter Plan",
    minDeposit: 10,
    maxDeposit: 29,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 1.0,
    dailyProfitUsdtMax: 2.9,
    durationDays: 60,
    totalUsers: 3245,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP2",
    level: "VIP 2",
    planName: "Basic Plan",
    minDeposit: 30,
    maxDeposit: 99,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 3.0,
    dailyProfitUsdtMax: 9.9,
    durationDays: 60,
    totalUsers: 2156,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP3",
    level: "VIP 3",
    planName: "Standard Plan",
    minDeposit: 100,
    maxDeposit: 299,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 10.0,
    dailyProfitUsdtMax: 29.9,
    durationDays: 60,
    totalUsers: 1984,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP4",
    level: "VIP 4",
    planName: "Advanced Plan",
    minDeposit: 300,
    maxDeposit: 999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 30.0,
    dailyProfitUsdtMax: 99.9,
    durationDays: 60,
    totalUsers: 1523,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP5",
    level: "VIP 5",
    planName: "Pro Plan",
    minDeposit: 1000,
    maxDeposit: 2999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 100.0,
    dailyProfitUsdtMax: 299.9,
    durationDays: 60,
    totalUsers: 890,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP6",
    level: "VIP 6",
    planName: "Expert Plan",
    minDeposit: 3000,
    maxDeposit: 6999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 300.0,
    dailyProfitUsdtMax: 699.9,
    durationDays: 60,
    totalUsers: 423,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP7",
    level: "VIP 7",
    planName: "Master Plan",
    minDeposit: 7000,
    maxDeposit: 14999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 700.0,
    dailyProfitUsdtMax: 1499.9,
    durationDays: 60,
    totalUsers: 18,
    status: "Active",
    referralBonus: { level1: 20, level2: 10, level3: 5 },
  },
  {
    id: "VP8",
    level: "VIP 8",
    planName: "Elite Plan",
    minDeposit: 15000,
    maxDeposit: 29999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 1500.0,
    dailyProfitUsdtMax: 2999.9,
    durationDays: 60,
    totalUsers: 42,
    status: "Active",
    referralBonus: { level1: 15, level2: 8, level3: 4 },
  },
  {
    id: "VP9",
    level: "VIP 9",
    planName: "Premium Plan",
    minDeposit: 30000,
    maxDeposit: 49999,
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 3000.0,
    dailyProfitUsdtMax: 4999.9,
    durationDays: 60,
    totalUsers: 1432,
    status: "Active",
    referralBonus: { level1: 10, level2: 5, level3: 2 },
  },
  {
    id: "VP10",
    level: "VIP 10",
    planName: "Ultimate Plan",
    minDeposit: 50000,
    maxDeposit: "Unlimited",
    dailyProfitPercent: 10.0,
    dailyProfitUsdtMin: 5000.0,
    dailyProfitUsdtMax: "Unlimited",
    durationDays: 60,
    totalUsers: 85,
    status: "Active",
    referralBonus: { level1: 15, level2: 8, level3: 4 },
  },
];

export const vipPlanBadgeStyles: Record<string, string> = {
  "VIP 1": "bg-blue-glow/10 text-blue-glow border border-blue-glow/20",
  "VIP 2": "bg-purple-bright/10 text-purple-bright border border-purple-bright/20",
  "VIP 3": "bg-warning/10 text-warning border border-warning/20",
  "VIP 4": "bg-danger/10 text-danger border border-danger/20",
  "VIP 5": "bg-emerald-400/10 text-emerald-400 border border-emerald-400/20",
  "VIP 6": "bg-amber-500/10 text-amber-500 border border-amber-500/20",
  "VIP 7": "bg-orange-500/10 text-orange-400 border border-orange-500/25",
  "VIP 8": "bg-red-800/10 text-red-400 border border-red-800/25",
  "VIP 9": "bg-fuchsia-500/10 text-fuchsia-400 border border-fuchsia-500/25",
  "VIP 10": "bg-purple-600/10 text-purple-400 border border-purple-600/25",
};
